[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "oldest-supported-numpy"]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "singlelaser/version.py"
