# Autogenerated by Astropy-affiliated package singlelaser's setup.py on 2022-01-07 00:57:54 UTC
import datetime

version = "0.1"
githash = "a160f8117024108de2b70481828b0607016e4063"


major = 0
minor = 1
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2022, 1, 7, 0, 57, 54)
debug = False

astropy_helpers_version = "4.0.1"
